### ISSUE TITLE
请教一个问题哈

### ISSUE THREAD

**Issue by 9a-aaaaaaaa** [dunwu/nginx-tutorial#1]
![image](https://user-images.githubusercontent.com/13470654/51954874-d2a3b700-247c-11e9-91f2-f847b3619b79.png)
这个地方的rootpei配置不生效，请问是不是有什么问题，既然反向代理了，root应该指向谁呢

**Comment by dunwu** [comment]
首先，很抱歉，一直没看到你的 issue。
然后，回答你的疑问：root 配置不生效，很大可能是路径不对（linux和windows下的路径分隔符是不同的）。
