### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by zhsongdanc** [dunwu/nginx-tutorial#29]
windows下访问后就到了nginx的页面，并不是目标页面

**Comment by ylzhen** [comment]
解决了吗

**Comment by ylzhen** [comment]
> windows下访问后就到了nginx的页面，并不是目标页面
解决了吗

**Comment by zhsongdanc** [comment]
没有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月17日(周五) 下午2:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dunwu/nginx-tutorial] 跑不起来 (Issue #29)




  
windows下访问后就到了nginx的页面，并不是目标页面
 解决了吗

**Comment by dunwu** [comment]
你的问题描述过于简单了。你是运行哪个示例时跑不起来？执行中有报错吗？

**Comment by dunwu** [comment]
> windows下访问后就到了nginx的页面，并不是目标页面

你的问题描述过于简单了。你是运行哪个示例时跑不起来？执行中有报错吗？
