### ISSUE TITLE
负载均衡策略參考連結失效

### ISSUE THREAD

**Issue by xxrjun** [dunwu/nginx-tutorial#32]
[Nginx 极简教程 - 负载均衡策略](https://github.com/dunwu/nginx-tutorial#%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1%E7%AD%96%E7%95%A5) 後方參考連結失效。

**Comment by dunwu** [comment]
@xxrjun 抱歉，之前一直未留意到您的回复，链接现已修复
